FROM node:14.17.3-alpine

# RUN npm install -g yarn

WORKDIR /usr

COPY package.json ./

COPY yarn.lock ./

COPY tsconfig.json ./

COPY src ./src

RUN ls -a

RUN yarn install

RUN yarn run build

## this is stage two , where the app actually runs

FROM node:14.17.3-alpine

WORKDIR /usr

COPY package.json ./

COPY yarn.lock ./

RUN yarn install --production=true

COPY --from=0 /usr/dist .

RUN yarn global add pm2

EXPOSE 80

CMD ["pm2-runtime","index.js"]